"""Drop-off Locator node: which kinds of facilities the scanned items need.

The mapping from materials and hazards to facility categories belongs to the Places
workstream (``app.places.categories``); this node only calls it, so the categories the
app searches with always match the facility search's own catalog. Facility names and
addresses are never generated by a model: the app fetches real places from
``/v1/facilities`` with these category keys.
"""

from __future__ import annotations

from app.ai.nodes.common import log, timed
from app.ai.state import RecommendState


@timed("dropoff")
async def dropoff_locator(state: RecommendState) -> dict:
    try:
        # Imported lazily so the AI pipeline never fails to import because of the Places package.
        from app.places.categories import categories_for_items  # noqa: PLC0415

        categories = categories_for_items(state["items"], state["lang"])
    except Exception as exc:
        log.warning("dropoff_locator failed, returning no facility categories: %r", exc)
        return {"facility_categories": [], "errors": {"dropoff": exc}}
    return {"facility_categories": list(categories)}
