/// POST /v1/facilities and GET /v1/facilities/categories
/// (mirror of `backend/app/schemas/facilities.py`).
///
/// Place data comes only from Google Places, OpenStreetMap and the team's curated
/// file; names, addresses and coordinates are never generated by a model.
library;

import 'package:freezed_annotation/freezed_annotation.dart';

import 'common.dart';
import 'recommend.dart';
import 'vocab_enums.dart';

part 'facilities.freezed.dart';
part 'facilities.g.dart';

/// Search request. Provide [lat] and [lng], or a [city] when there is no GPS fix.
@freezed
abstract class FacilitiesRequest with _$FacilitiesRequest {
  @Assert('categories.length > 0', 'At least one category key is required.')
  @Assert(
    '(lat != null && lng != null) || city != null',
    'Provide lat and lng, or a city.',
  )
  const factory FacilitiesRequest({
    required List<String> categories,
    double? lat,
    double? lng,
    CityId? city,
    @Default(15000) int radiusM,
    @Default(20) int limit,
    @Default(Lang.en) Lang lang,
  }) = _FacilitiesRequest;

  factory FacilitiesRequest.fromJson(Map<String, dynamic> json) =>
      _$FacilitiesRequestFromJson(json);
}

/// Where a place record comes from.
enum PlaceSource {
  @JsonValue('google')
  google,
  @JsonValue('osm')
  osm,
  @JsonValue('curated')
  curated,
}

@freezed
abstract class Place with _$Place {
  const factory Place({
    /// 'g:<place id>', 'osm:<type>/<id>' or 'cur:<id>'.
    required String id,
    required String name,
    String? address,
    required double lat,
    required double lng,
    int? distanceM,
    bool? openNow,
    String? phone,
    String? website,

    /// Deep link that opens this place in Google Maps.
    String? mapsUrl,
    required List<FacilityType> facilityTypes,

    /// Which requested categories this place matched.
    required List<String> categoryKeys,

    /// Only when the source states it.
    List<MaterialCategory>? acceptedMaterials,
    String? acceptedNote,
    double? rating,
    required PlaceSource source,
  }) = _Place;

  factory Place.fromJson(Map<String, dynamic> json) => _$PlaceFromJson(json);
}

@freezed
abstract class FacilitiesResponse with _$FacilitiesResponse {
  const factory FacilitiesResponse({
    /// Sorted by distance, nearest first.
    required List<Place> places,
    required GeoPoint center,

    /// City name or 'Your location', localized.
    required String centerLabel,
    required List<PlaceSource> sourcesUsed,

    /// Localized note, e.g. when only OpenStreetMap data is available.
    String? notice,
    @Default(<String, int>{}) Timings timingsMs,
  }) = _FacilitiesResponse;

  factory FacilitiesResponse.fromJson(Map<String, dynamic> json) =>
      _$FacilitiesResponseFromJson(json);
}

@freezed
abstract class FacilityCategoriesResponse with _$FacilityCategoriesResponse {
  const factory FacilityCategoriesResponse({
    required List<FacilityCategory> categories,
    required Lang lang,
  }) = _FacilityCategoriesResponse;

  factory FacilityCategoriesResponse.fromJson(Map<String, dynamic> json) =>
      _$FacilityCategoriesResponseFromJson(json);
}
