"""POST /v1/facilities and GET /v1/facilities/categories: nearby drop-off points.

Live data only (Google Places API (New) Text Search, OpenStreetMap Overpass fallback,
plus team-verified curated entries). Facility names, addresses and coordinates are
never generated by an LLM.
"""

from typing import Literal

from pydantic import Field, model_validator

from app.schemas.common import ApiModel, LatLng, Timings
from app.schemas.recommend import FacilityCategory
from app.schemas.vocab import CityId, FacilityType, Lang, MaterialCategory


class FacilitiesRequest(ApiModel):
    categories: list[str] = Field(min_length=1, description="FacilityCategory keys to search for.")
    lat: float | None = Field(default=None, ge=-90, le=90)
    lng: float | None = Field(default=None, ge=-180, le=180)
    city: CityId | None = Field(default=None, description="Used when there is no GPS fix.")
    radius_m: int = Field(default=15000, ge=500, le=60000)
    limit: int = Field(default=20, ge=1, le=60)
    lang: Lang = "en"

    @model_validator(mode="after")
    def _needs_location(self) -> "FacilitiesRequest":
        if (self.lat is None or self.lng is None) and self.city is None:
            raise ValueError("Provide lat and lng, or a city.")
        return self


class Place(ApiModel):
    id: str = Field(description="'g:<place id>', 'osm:<type>/<id>' or 'cur:<id>'.")
    name: str
    address: str | None = None
    lat: float
    lng: float
    distance_m: int | None = None
    open_now: bool | None = None
    phone: str | None = None
    website: str | None = None
    maps_url: str | None = Field(default=None, description="Deep link that opens this place in Google Maps.")
    facility_types: list[FacilityType]
    category_keys: list[str] = Field(description="Which requested categories this place matched.")
    accepted_materials: list[MaterialCategory] | None = Field(
        default=None, description="Only when the source states it."
    )
    accepted_note: str | None = None
    rating: float | None = None
    source: Literal["google", "osm", "curated"]


class FacilitiesResponse(ApiModel):
    places: list[Place] = Field(description="Sorted by distance, nearest first.")
    center: LatLng
    center_label: str = Field(description="City name or 'Your location', localized.")
    sources_used: list[Literal["google", "osm", "curated"]]
    notice: str | None = Field(
        default=None, description="Localized note, e.g. when only OpenStreetMap data is available."
    )
    timings_ms: Timings = Field(default_factory=dict)


class FacilityCategoriesResponse(ApiModel):
    categories: list[FacilityCategory]
    lang: Lang
